### PR TITLE
Nuttx v11.0 with jupiter nano support

### PR DESCRIPTION
**Pull request by JakeSays**
## Summary

This pr contains upstream nuttx branch `releases/11.0` with updated jupiter nano support. 

Compiles and runs against nuttx-apps branch `releases/11.0`.

I do apologize for the large number of commits. I was going to squash them but I thought you might want the upstream commit history.

### CODE REVIEW

**Comment by adamfeuer** [comment]
@JakeSays Hey, what gcc toolchain are you using? I can't get the standard `releases/11.0` branch to compile and run successfully with my toolchains (ARM GNU Toolchain v9, v10, or v11 for Linux).

I can compile my old 10.x branch with ARM GNU Toolchain v11 though. 

Are you using a different compiler or toolchain? If so, which one?

**Comment by JakeSays** [comment]
@adamfeuer here's the output of `arm-none-eabi-gcc --version`.  It's from ubuntu 22.04.

arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by adamfeuer** [comment]
@JakeSays Thank you. I am using Ubuntu 22.04 with the same compiler.

However, I can't compile my master after merging your branch, and I can't compile your branch either... I am not sure what is wrong. 

I have the `apps/` repo set to the `releases/11.0` branch, and I'm using your `JakeSays/incubator-nuttx/jupiter-nano-support` branch.

Here's the error I am getting:

```
arm-none-eabi-gcc: warning: /home/adam/src/nuttx/nuttx-sama5d2-xult-jakesays/apps/include: linker input file unused because linking not done
./exec_builtin.c:32:10: fatal error: builtin/builtin.h: No such file or directory
   32 | #include "builtin/builtin.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
ERROR: arm-none-eabi-gcc failed: 1
       command: arm-none-eabi-gcc -MT ./exec_builtin.c.home.adam.src.nuttx.nuttx-sama5d2-xult-jakesays.apps.builtin.o  -M '-fno-builtin' '-Wall' '-Wstrict-prototypes' '-Wshadow' '-Wundef' '-Os' '-fno-strict-aliasing' '-fno-strength-reduce' '-fomit-frame-pointer' '-mcpu=cortex-a5' '-mfpu=vfpv4-d16' '-isystem' '/home/adam/src/nuttx/nuttx-sama5d2-xult-jakesays/nuttx/include' '-D__NuttX__' '-D__KERNEL__' '-pipe' '/home/adam/src/nuttx/nuttx-sama5d2-xult-jakesays/apps/include' ./exec_builtin.c
```

This happens when I try to compile for `jupiter-nano:nsh` or `sama5d2-xult:nsh` (or other configs too). Have you seen this? I think something is different between our setups.

The file `builtin.h` does exist though, in the `apps/` directory:

```
$ find . -iname "builtin.h"
./include/builtin/builtin.h
```

**Comment by JakeSays** [comment]
@adamfeuer Hey sorry for the late reply. I got a bit side tracked. I'll take a look now.

**Comment by JakeSays** [comment]
@adamfeuer here's a defconfig generated from my current .config: https://gist.github.com/JakeSays/20e29c704ea474346e47ccda529baf63

Not sure if that helps.

**Comment by adamfeuer** [comment]
Thanks, it was helpful. 

Using your defconfig I was able to get the system `arm-none-eabi-gcc` to compile NuttX.

Then I worked out what the problem was. NuttX could boot just fine in the JTAG debugger (OpenOCD/GDB) but not from the SDMMC card. This was because NuttX's start address in the 10.x versions is `0x20008040`, but in 11.x or 12.x it is `0x200082e0`. GDB knew the start address from looking at the binary and used it automatically.

But when booting from U-Boot, it doesn't know that. I needed to set the `bootcmd` to start at this address:

```
bootcmd=fatload mmc 1 0x20008000 nuttx.bin ; fatload mmc 1 0x20008000 nuttx.bin ; go 0x200082e0
```

Everything is working now. Thank you!

**Comment by JakeSays** [comment]
Ah yes I forgot about the start address. I ran in to this issue when I built my own at91bootstrap that loaded nuttx directly.

**Pull request merged**
